version: "3.7"
services:
    pkg:
        build:
          context: .
          dockerfile: Dockerfile.local
        ports:
            - "0.0.0.0:5001:5001"
        depends_on:
            - db
        networks: 
            - ipost-network
    db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
          - sqlvolume:/var/opt/mssql

        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "0.0.0.0:1433:1433"
        networks: 
            - ipost-network

volumes:
  sqlvolume:

networks:
    ipost-network:
        external: true