version: "3.7"
services:
    pkg:
        build: .
        ports:
            - "5001:5001"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "7000:1433"
        volumes:
            - sqlserver:/sqlserver
volumes:
    sqlserver:
        driver: local