name: Build and test .NET API
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['3.1.x']
    name: Dotnet ${{ matrix.dotnet }} build and test
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
  
      - uses: microsoft/variable-substitution@v1 
        with:
            files: 'appsettings.json'
        env:
            ConnectionString: "${{ secrets.DATABASE_CONNECTION }}"
          
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: | 
        dotnet build
        dotnet test
